apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: customer
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - customer.keptnorders-staging.34.77.151.116.xip.io
  - customer
  http:
  - route:
    - destination:
        host: customer.keptnorders-staging.svc.cluster.local
